### ISSUE TITLE
build error vite 2.8.0 error

### ISSUE THREAD

**Issue by cuing** [jy0529/vite-plugin-dynamic-publicpath#12]
vite 2.8.0 use 「useDynamicPublicPath」plugin，build with error:

`error during build:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.basename (path.js:1156:5)
    at Object.generateBundle (/Users/****/node_modules/vite/dist/node/chunks/dep-c9c9d3e5.js:29846:56)
    at /Users/****/node_modules/rollup/dist/shared/rollup.js:22681:25
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

without 「useDynamicPublicPath」,build is ok。

**Comment by jy0529** [comment]
can you support a reproduce demo ? 
I try to upgrade vite2.8 in examples, it's run ok.
