### ISSUE TITLE
build error in vite@v3.0.6beta

### ISSUE THREAD

**Issue by GitYiM** [jy0529/vite-plugin-dynamic-publicpath#17]
[vite:build-import-analysis] Cannot read property 'type' of undefined
error during build:
TypeError: Cannot read property 'type' of undefined
    at Object.generateBundle (file:///Users/workplace/public-path/node_modules/vite/dist/node/chunks/dep-c7f6d0a5.js:40589:27)
    at file:///Users/workplace/public-path/node_modules/rollup/dist/es/shared/rollup.js:22739:37

**Comment by it-xtech-dev** [comment]
Same on my side.

```
$ vite build
vite v2.9.9 building for production...
✓ 41 modules transformed.
rendering chunks (8)...[vite:build-import-analysis] Cannot read property 'type' of undefined
error during build:
TypeError: Cannot read property 'type' of undefined
    at Object.generateBundle (...\node_modules\vite\dist\node\chunks\dep-59dc6e00.js:38155:27)
    at ...\node_modules\rollup\dist\shared\rollup.js:23038:37
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
error Command failed with exit code 1.
```
